# Generated by Django 3.1.3 on 2020-12-03 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20201130_1155'),
        ('market', '0003_market_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compinfo',
            name='adminid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='adminid', to='login.user'),
        ),
        migrations.AlterField(
            model_name='compinfo',
            name='userac',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='userac', to='login.user', to_field='name'),
        ),
        migrations.AlterField(
            model_name='compinfo',
            name='userpa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='userpa', to='login.user', to_field='name'),
        ),
    ]
