# Generated by Django 2.2.4 on 2019-08-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('seats', models.CharField(max_length=128)),
                ('addinfo', models.CharField(max_length=128)),
                ('departure', models.CharField(max_length=128)),
                ('destination', models.CharField(max_length=128)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
