# Generated by Django 3.1.3 on 2020-12-03 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20201130_1155'),
        ('market', '0004_auto_20201203_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compinfo',
            name='adminid',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='compinfo',
            name='userac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userac', to='login.user', to_field='name'),
        ),
        migrations.AlterField(
            model_name='compinfo',
            name='userpa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userpa', to='login.user', to_field='name'),
        ),
    ]
