# Generated by Django 3.1.3 on 2021-01-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user_imgpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imgpath',
            field=models.CharField(default='default.jpg', max_length=128),
        ),
    ]
