# Generated by Django 3.1.3 on 2020-12-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20201203_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='safe',
            field=models.FloatField(default=100.0),
        ),
    ]
