# Generated by Django 3.1.3 on 2020-12-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_market_safe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='safe',
            field=models.IntegerField(),
        ),
    ]
